version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nodeApp/on-prem/
 
hooks:
  BeforeInstall:
    - location: scripts/echo.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/list.sh
      timeout: 180
      runas: root
